### ISSUE TITLE
TradingBot hit a require or revert statement somewhere in its constructor. 

### ISSUE THREAD

**Issue by Nisthar** [ExtropyIO/defi-bot#11]
I get this error when running `truffle migrate` on ganache development blockchain. 

```
TradingBot" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.
   ```

**Comment by restorepro** [comment]
Did you add the console.table? npm install console.table --save

**Comment by Nisthar** [comment]
@restorepro its the same after installing node_modules

**Comment by Nisthar** [comment]
```
TradingBot" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.
   ```

**Comment by restorepro** [comment]
Are you using VS Code as your ide?

**Comment by Nisthar** [comment]
@restorepro Yes i am using vs code. also i am not using remix to deploy like it says in the readme. But I am deploying it on a ganache development tool.

**Comment by restorepro** [comment]
Ok. The only truffle related issue that I had was the compiler version of the smart contract (FlashLoan.sol) was throwing a error when i ran 'truffle migrate' so I had to change it to ^0.5.17 from ^0.5.0 in vs code...  Have you tried at all using Remix just to see if it works?

**Comment by restorepro** [comment]
I was able to get it to deploy using vs Code and truffle to the ropsten testnet... I coudnt get ganache to work.
<img width="1026" alt="Screen Shot 2021-06-01 at 7 33 25 PM" src="https://user-images.githubusercontent.com/5422783/120402540-75e88d80-c310-11eb-869a-c1029254c648.png">

**Comment by restorepro** [comment]
Did you modify the truffle-config.js file and add 2_deploy_contracts.js file to the Migrations folder? I also had to change the flashloan.sol file compiler version to ^0.5.17 in the solidity file and the truffle-config.js file and then run truffle compile.
<img width="1023" alt="Screen Shot 2021-06-01 at 7 42 46 PM" src="https://user-images.githubusercontent.com/5422783/120403120-8fd6a000-c311-11eb-9162-3022deafd923.png">

**Comment by Nisthar** [comment]
Thanks I was trying to migrate the TradingBot.sol maybe i have to change it to the flashloan.sol. Have you tried compiling the contracts with hardhat instead?

**Comment by restorepro** [comment]
No i haven't tried using Hardhat yet but I will probably try and deploy it this weekend with Hardhat.  Im still getting an error when I run the index.js file though..
<img width="1167" alt="Screen Shot 2021-06-02 at 6 15 23 PM" src="https://user-images.githubusercontent.com/5422783/120559153-85c6a700-c3ce-11eb-80d5-575e2d990a44.png">

**Comment by Nisthar** [comment]
Thanks, i got it working with hardhat. But i am still getting the Insufficient funds error.

**Comment by restorepro** [comment]
Glad you got it deployed! Is your GAS error the same as mine?
