### ISSUE TITLE
ts(1005) Error 

### ISSUE THREAD

**Issue by bizraelii** [ExtropyIO/defi-bot#16]
![defi bot error](https://user-images.githubusercontent.com/86215833/122702515-65874c80-d204-11eb-9b0e-df7d6e252b70.JPG)

A few things I've tried:
- Put a semicolon and comma at the end
- Disabled TypeScript and JavaScript Language Features

Typescript version 4.3.4
VS Code 1.57.1
Windows 10

Any ideas on what the actual issue is, and how to fix it?

Thanks

**Comment by codemedici** [comment]
"Perform Trade" is just a comment, you must have removed // in front by mistake :)
