### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by eazd** [ExtropyIO/defi-bot#23]
Bye

**Comment by codemedici** [comment]
@eazd if you got scammed by somebody it is not our fault, if you open an issue it will seem like we scammed you which is not the case! If you message me describing the scam I will open an issue so that other people don't fall for it.

**Comment by eazd** [comment]
@codemedici I will message you with all the details

**Comment by eazd** [comment]
> @eazd if you got scammed by somebody it is not our fault, if you open an issue it will seem like we scammed you which is not the case! If you message me describing the scam I will open an issue so that other people don't fall for it.
Can you please message me, I have tried to message your but I couldn't find a way. Thanks!
