### ISSUE TITLE
Is the second article still coming ?

### ISSUE THREAD

**Issue by tudorelu** [ExtropyIO/defi-bot#5]
What the title says. Really keen to understand the code!

**Comment by codemedici** [comment]
https://extropy-io.medium.com/arbitrage-bot-part-2-97e7b710dcf

Don't trade on main St until you understand what you are doing! Errors are costly. Comment out the contract call inside index.js or the best way for testing is to simulate using contracts on a testnet

**Comment by tudorelu** [comment]
Thank you kindly

**Comment by Nisthar** [comment]
@codemedici can you tell me what are the steps for using testnets? do i need to edit the smart contract (replace with testnet addresses) Right?

**Comment by ccarnino** [comment]
I am also interested in this. I am also trying to query 0x APIs on Ropsten without much success

**Comment by cosimo-de-medici** [comment]
The best approach is to fork mainnet with [ganache-cli ](https://github.com/trufflesuite/ganache-cli) like this:
`ganache-cli -p 7545 --fork mainnet`
Then make sure that in truffle-config.js your "development" network is configured to connect to localhost:7545

@Nisthar @ccarnino @tudorelu

**Comment by Nisthar** [comment]
@cosimo-de-medici i already have the ganache gui installed. also added the "development" options in truffle. Do you think its the same?
