### ISSUE TITLE
What is the optimum values for Gas For Arb to Run

### ISSUE THREAD

**Issue by ratewar** [ExtropyIO/defi-bot#6]
Hi thanks for the article and code. The challenge i have is getting the optimum value for Gas for Arb. How much is sufficient is the value provided in .env is the right values ? It turns out to be too much cost from a txn fee prospective.

**Comment by codemedici** [comment]
Hi, you can use https://docs.ethgasstation.info/ API in order to always use the best price dynamically, I recommend using the fastest option and update the profit calculation with the dynamic gas amount each time.
